### ISSUE TITLE
9.0 and 9.1 images request

### ISSUE THREAD

**Issue by gotero** [hpcng/warewulf-node-images#1]
Request for WW compute node images for Rocky Linux 9.0 and 9.1

**Comment by rthomson** [comment]
I submitted PR #13 to add Rocky Linux 9 image builds to the repo. I wanted them for me but hopefully they work for others as well!

**Comment by anderbubble** [comment]
Thanks, @rthomson! I've taken a note to review your PR and hopefully merge it in! But I'll let you know.

**Comment by anderbubble** [comment]
@gotero can you check out the Rocky Linux 9 image that was just merged?

@rthomson would you be willing to add tagged 9.0 and 9.1 containers as well? Examples are present for 8.6 and 8.7 (though I'd like to adjust those such that the non-tagged repositories are more permanently disabled so that downstream containers stick to the point release).

**Comment by rthomson** [comment]
@anderbubble Certainly, I'll look into adding tagged containers pinned to point releases for `rockylinux-9`, using `rockylinux-8` as an example.

**Comment by rthomson** [comment]
@anderbubble PR #14 adds container builds pinned to the 9.0 and 9.1 releases.
